name: Run Jest Tests 2

on:
  push:
    branches:
      - 'main'

jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                node-version: '20'

            - name: Install Dependencies
              run: npm install

            - name: Install Jest
              run: npm install jest -g

            - name: Run Jest Test 2
              run: jest tests/2.test.js
